version: "2.1"
services:
  webtop:
    buildCommand: "docker build -t render-ultralight ."
    dockerfilePath: ./Dockerfile
    image: render-ultralight
    env:
      - key: DISPLAY
        value: ":1"
    ports:
      - 6080:6080
    restart: always
    shm_size: "512mb"
    autoDeploy: true
