services:
  - type: web
    name: ubuntu-novnc
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: PASS
        value: "ubuntu"
      - key: PORT
        value: "6080"
