version: "2.1"
services:
  webtop:
    buildCommand: "docker build -t render-ultralight ."
    dockerfilePath: ./Dockerfile
    image: render-ultralight
    ports:
      - 6080:6080
    restart: always
    autoDeploy: true
