services:
  - type: web
    name: ubuntu-novnc
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: DISPLAY_WIDTH
        value: "1600"
      - key: DISPLAY_HEIGHT
        value: "900"
      - key: PORT
        value: "6080"
