# ─────────────────────────────────────────────
# render.yaml
# ─────────────────────────────────────────────
services:
  - type: web
    name: ubuntu-novnc
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true
    ports:
      - port: 6080
        protocol: http
    healthCheckPath: /
    buildCommand: docker build -t ubuntu-novnc .
    startCommand: docker run -i -t -p 6080:6080 ubuntu-novnc
