services:
  - type: web
    name: ubuntu-novnc
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true
    ports:
      - port: 6080
        protocol: http
    healthCheckPath: /
    startCommand: bash -c "\
      rm -f /tmp/.X1-lock /tmp/.X11-unix/X1 && \
      Xvfb :1 -screen 0 1280x720x24 & \
      sleep 2 && \
      fluxbox & \
      x11vnc -display :1 -nopw -forever -shared & \
      websockify --web=/usr/share/novnc/ 6080 localhost:5900 & \
      wait"
